# Generated by Django 2.2.4 on 2019-08-15 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_activate',
            new_name='is_active',
        ),
    ]
